name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    # - name: Print a welcome message
    #   run: echo "Hello, CI/CD!"

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: setup .NET SDK
      uses: actions/setup-dotnet@v4
      with: 
        dotnet-version: '10.0.x'
    
    # - name: print dotnet version 
    #   run: dotnet --version

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build 
      run: dotnet build --no-restore --configuration Release

    - name: Run Tests
      run: dotnet test --no-build --configuration Release --verbosity normal
      
    - name: Publish 
      run: dotnet publish CicdDotnetDemo.Api/CicdDotnetDemo.Api.csproj --no-build --configuration Release --output ./publish
    