name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    # - name: Print a welcome message
    #   run: echo "Hello, CI/CD!"

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: setup .NET SDK
      uses: actions/setup-dotnet@v4
      with: 
        dotnet-version: '10.0.x'
    
    # - name: print dotnet version 
    #   run: dotnet --version

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build 
      run: dotnet build --no-restore --configuration Release

    - name: Run Tests
      run: dotnet test --no-build --configuration Release --verbosity normal
      
    - name: Publish 
      run: dotnet publish CicdDotnetDemo.Api/CicdDotnetDemo.Api.csproj --no-build --configuration Release --output ./publish
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cicd-dotnet-demo-api
        path: ./publish
        retention-days: 7

    - name: Test Secret Masking
      env:
        SUPER_SECRET: ${{ secrets.MY_SUPER_SECRET }}
      run: |
        echo "The secret is: $SUPER_SECRET"
        echo "Notice how GitHub hides it!"

  deploy-to-staging:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: Staging
    
    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: cicd-dotnet-demo-api
        path: ./publish

    - name: Simulate Deployment
      run: |
        echo "Deploying to Staging Server..."
        echo "Copying files from ./publish..."
        # Here is where you would run real deployment commands (Azure, AWS, SSH, etc.)
        echo "Deployment Successful!"

    


    